//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewsLayer.ServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaintenanceEmpresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MaintenanceEmpresa(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MaintenanceEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MaintenanceEmpresaAsync(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListEmpresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetListEmpresa(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListEmpresa", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetListEmpresaAsync(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ViewsLayer.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ViewsLayer.ServiceReference.WebServiceSoap>, ViewsLayer.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MaintenanceEmpresa(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION) {
            return base.Channel.MaintenanceEmpresa(pID_COMPAÑIA, pNOMBRE, pUBICACION, pEMAIL, pTELEFONO, pACCION);
        }
        
        public System.Threading.Tasks.Task<string> MaintenanceEmpresaAsync(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION) {
            return base.Channel.MaintenanceEmpresaAsync(pID_COMPAÑIA, pNOMBRE, pUBICACION, pEMAIL, pTELEFONO, pACCION);
        }
        
        public System.Data.DataSet GetListEmpresa(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION) {
            return base.Channel.GetListEmpresa(pID_COMPAÑIA, pNOMBRE, pUBICACION, pEMAIL, pTELEFONO, pACCION);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetListEmpresaAsync(string pID_COMPAÑIA, string pNOMBRE, string pUBICACION, string pEMAIL, string pTELEFONO, string pACCION) {
            return base.Channel.GetListEmpresaAsync(pID_COMPAÑIA, pNOMBRE, pUBICACION, pEMAIL, pTELEFONO, pACCION);
        }
    }
}
